networks:
  laravel:
    name: laravel
    driver: bridge

services:
  app:
    container_name: laravel_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/marco
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: unless-stopped
    working_dir: /var/www/marco
    networks:
      - laravel
    # ports:
    #     - "5173:5173"

  web:
    container_name: laravel_web
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "90:80"
    volumes:
      - .:/var/www/marco
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql:latest
    container_name: laravel_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    volumes:
      - ./docker/postgres/data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - laravel

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - laravel

  # adminer:
  #   container_name: adminer_container
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "7070:8080"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64 # for mac
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "9090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "1234"
    depends_on:
      - db
    networks:
      - laravel

  # redis:
  #   image: redis:latest
  #   container_name: laravel_redis
  #   restart: unless-stopped
  #   networks:
  #     - laravel

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq_container
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"   # RabbitMQ message broker port
    networks:
      - laravel

volumes:
  dbdata:
  postgres_data:
  mongo_data:
